### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by varlesh** [PapirusDevelopmentTeam/papirus-icon-theme-kde#1]
@FadeMind please help i can't add new icon to repo. Use gitkraken, show this:
![screenshot_20160602_175331](https://cloud.githubusercontent.com/assets/8083855/15749420/fa146dd8-28ea-11e6-9e93-08d8ba33016d.png)

**Comment by varlesh** [comment]
I'm on Collaborators, but can't pushed. Why?

**Comment by FadeMind** [comment]
@varlesh You are now admin.

**Comment by FadeMind** [comment]
FOR each one repo we need setup 

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-kde/settings/collaboration

collaboration page

**Comment by varlesh** [comment]
Im Collabrator, but
fatal: Authentication failed for 'https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-kde.git/'

**Comment by FadeMind** [comment]
SSH is set?

**Comment by varlesh** [comment]
On gitkraken use ssh

**Comment by FadeMind** [comment]
You need login via SSH

VALID URL

git@github.com:PapirusDevelopmentTeam/papirus-icon-theme-kde.git

**Comment by FadeMind** [comment]
I gave you bash script for all xD

**Comment by varlesh** [comment]
Ok. thx i found him

**Comment by varlesh** [comment]
@FadeMind I need apply this instructions?
@varlesh 
You need to configure your SSH agent for easy push comits (without promt password ANY TIME)

Install required packages: `openssh` `gnupg` `kwalletmanager` `kwallet` `kwalletcli` `pinentry` `ksshaskpass`.
**1. Create a file:**

**$HOME/.config/systemd/user/ssh-agent.service**
```
[Unit]
Description=SSH key agent

[Service]
Type=forking
Environment=SSH_AUTH_SOCK=%t/ssh-agent.socket
ExecStart=/usr/bin/ssh-agent -a $SSH_AUTH_SOCK

[Install]
WantedBy=default.target
```

ENABLE and START service for USER:

```
systemctl --user enable ssh-agent;systemctl --user start ssh-agent
```

**2. Add value `SSH_ASKPASS` to `.bash_profile` file.**

$HOME/.bash_profile
```
#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# additional local bin directory (based on my setup)
export PATH="${PATH}:/home/tomasz/bin"
# QT plugin path (based on my setup)
export QT_PLUGIN_PATH="/usr/lib/qt/plugins"
# set SSH_ASKPASS value
export SSH_ASKPASS="/usr/bin/ksshaskpass"
```


**3. edit file `$HOME/.ssh/config`**
```
IdentityFile ~/.ssh/id_rsa
User FadeMind # my user name -here paste yours
ForwardAgent yes
```
**4. Add to `.bashrc`
```
# Running ssh-agent after launch terminal
eval `ssh-agent -s` > /dev/null && ssh-add $HOME/.ssh/id_rsa $HOME/.ssh/id_rsa-aur </dev/null 1>&- 2>&-
```
Reload SH:
```
source .bashrc
```

Always after open new konsole window - new SSH agent AUTH will be done.
<hr/>

USE this simple script for download and access repos (update):

```
#!/bin/bash
SSH_ACCESS="git@github.com:PapirusDevelopmentTeam"
REPO=(bomi-skin-papirus libreoffice-papirus-theme papirus-aurorae-theme papirus-color-scheme papirus-gtk-theme papirus-icon-theme-gtk papirus-icon-theme-kde papirus-k3b-theme papirus-kmail-theme papirus-konsole-colorscheme papirus-look-and-feel papirus-plasma-theme papirus-qtcurve-theme papirus-sddm-theme papirus-smplayer-theme papirus-vlc-theme papirus-wallpapers papirus-yakuake-theme)

for r in ${REPO[@]}
do 
    if [ ! -d "$r" ]; then
        git clone $SSH_ACCESS/$r
    else
        echo "DIR $r exists"
    fi
done
```

**Comment by FadeMind** [comment]
IF you want enter SSH PASS EVERY TIME - no ;D

Reference: https://wiki.archlinux.org/index.php/SSH_keys#ssh-agent

**Comment by varlesh** [comment]
omg. Why i can't push on gitkraken?

**Comment by FadeMind** [comment]
@varlesh what it is?  :>

**Comment by varlesh** [comment]
GUI for git with ssh
https://www.gitkraken.com/

**Comment by FadeMind** [comment]
@varlesh I will take care of setup gitkraken later, I am busy here.

**Comment by varlesh** [comment]
@FadeMind you can push anything on new any repo?

**Comment by FadeMind** [comment]
@varlesh 
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-gtk/commit/959d3bb6a4981f3c5c2509c244a5d67604c9ba94

I using simple command

```
[tomasz@arch papirus-icon-theme-gtk]$ git add --all && git commit -S -am 'AUTHORS: update URL' && git push origin master[master 959d3bb] AUTHORS: update URL
 1 file changed, 1 insertion(+), 1 deletion(-)
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 997 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
To git@github.com:PapirusDevelopmentTeam/papirus-icon-theme-gtk
   3ddcf1b..959d3bb  master -> master
[tomasz@arch papirus-icon-theme-gtk]$ pwd
/home/tomasz/dev/GITHUB/PapirusDevTeam/papirus-icon-theme-gtk
[tomasz@arch papirus-icon-theme-gtk]$ 
```

**Comment by FadeMind** [comment]
And so on:
```
[tomasz@arch papirus-icon-theme-gtk]$ cd ../papirus-icon-theme-kde/
[tomasz@arch papirus-icon-theme-kde]$ git add --all && git commit -S -am 'AUTHORS: update URL' && git push origin master
[master 08a8f56] AUTHORS: update URL
 1 file changed, 1 insertion(+), 1 deletion(-)
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 997 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
To git@github.com:PapirusDevelopmentTeam/papirus-icon-theme-kde
   3e26848..08a8f56  master -> master
[tomasz@arch papirus-icon-theme-kde]$ 
```

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-kde/commit/08a8f56a5e71c0d892c5ccf26d6a9c2cd2410195

**Comment by FadeMind** [comment]
You have corrupted setup on your local.

**Comment by varlesh** [comment]
@FadeMind Thx for help, working on command line )
