### ISSUE TITLE
[Icon request] Heroes of Newerth

### ISSUE THREAD

**Issue by gustawho** [PapirusDevelopmentTeam/papirus-icon-theme-kde#4]
If possible, could you please create an icon for this game?

Here the original icon:
![honicon_128x128](https://cloud.githubusercontent.com/assets/2186602/17576946/863460ea-5f35-11e6-9342-c8a5be9a927a.png)

**Comment by varlesh** [comment]
done

**Comment by varlesh** [comment]
@gustawho you know icon name? I added only **heroesofnewerth** and symlink **hon**

**Comment by varlesh** [comment]
upd: On AUR found also **honicon_128x128**, but this icon hardcoded. You must replace icon name manually:
```
[Desktop Entry]
Encoding=UTF-8
Name=Heroes of Newerth
GenericName=Heroes of Newerth
Comment=
Exec=/usr/bin/hon
Icon=/opt/hon/honicon_128x128.png
StartupNotify=true
Terminal=false
Type=Application
Categories=Application;Game
```
