### ISSUE TITLE
Icon Request: Rambox

### ISSUE THREAD

**Issue by AndydeCleyre** [PapirusDevelopmentTeam/papirus-icon-theme-kde#5]
Hi,

Thanks for the continued work on this set!

[Rambox](http://rambox.pro/) wraps a bunch of web interfaces for chat and email services in a desktop app.  I don't know where the name comes from or what the upstream icon is supposed to be, exactly, but I'm uploading it here:

![rambox](https://cloud.githubusercontent.com/assets/1787385/17601196/ee12df80-5fd4-11e6-921c-ef04c33d1850.png)

**Comment by varlesh** [comment]
on AUR desktop-file contains Icon=rambox

**Comment by varlesh** [comment]
![rambox](https://cloud.githubusercontent.com/assets/8083855/17641878/3de389ea-613a-11e6-9031-010a9de47122.png)
