### ISSUE TITLE
Copy redshift status icons from papirus-icon-theme-gtk

### ISSUE THREAD

**Issue by AndydeCleyre** [PapirusDevelopmentTeam/papirus-icon-theme-kde#6]
Hi,

Please include the redshift status icons that are available in papirus-icon-theme-gtk:

```
Papirus-GTK/{22x22,24x24}/panel/redshift-status-{on,off}.svg
```

**Comment by varlesh** [comment]
added 22px only, because on > Plasma 5.7 use only 22px on tray.
