### ISSUE TITLE
Caffeine tray icon quality is really low on HIDPI screens

### ISSUE THREAD

**Issue by justanotherjason** [PapirusDevelopmentTeam/papirus-icon-theme-kde#9]
Hi,

I'm using a hidpi screen with a 2880x1800 resolution. All the icons seem great except the caffeine tray icon. You can barely say that is a coffee cup. I am attaching a screenshot for reference.

![screenshot_20161001_004400](https://cloud.githubusercontent.com/assets/12893468/18997668/6e125270-8770-11e6-88d8-a8626b2b8006.png)

**Comment by varlesh** [comment]
icon vector, maybe this plasma bug:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-kde/blob/081813d70afb33dfd94067f91f3aa877de7f7ff2/papirus/22x22/status/caffeine-cup-empty.svg
